name: dagger
on:
  push:
    branches: [trunk]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Install Dagger CLI
        run: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sh; cd -; }
      - name: Run Dagger pipeline
        env:
          GH_SECRET=${{ secrets.GH_SECRET }}
        run: dagger run go run ci/main.go
